image:
  repository: 172.16.16.2:30516/external-secrets/external-secrets
  pullPolicy: IfNotPresent  
  tag: "v0.9.20"

certController:
  image:
    repository: 172.16.16.2:30516/external-secrets/external-secrets
    pullPolicy: IfNotPresent  
    tag: "v0.9.20"

webhook:
  image:
    repository: 172.16.16.2:30516/external-secrets/external-secrets
    pullPolicy: IfNotPresent  
    tag: "v0.9.20"

resources:
  requests:
    cpu: 100m
    memory: 200Mi
  limits:
    cpu: 100m
    memory: 200Mi    

global:
  nodeSelector: 
    node.name: node-1
  tolerations: []