apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: auth
  namespace: argocd
spec:
  project: default
  destination:
    namespace: kube-system
    server: https://kubernetes.default.svc
  sources:
    - repoURL: https://github.com/behrooz/application.git
      targetRevision: HEAD
      path: bugx/authservice
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
