apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sysbox
  namespace: argocd
spec:
  destination:
    namespace: kube-system
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/behrooz/application.git
    targetRevision: HEAD
    path: backing-services/sysbox
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true