global:
  imageRegistry: ""
  imagePullSecrets: []
  storageClass: ""

auth:
  rootPassword: "secret123"
  createDatabase: true
  database: "my_database"
  username: "admin"
  password: "secret123"
  replicationUser: replicator
  replicationPassword: ""
  existingSecret: ""
  usePasswordFiles: false
  customPasswordFiles: {}
  defaultAuthenticationPlugin: ""  