global:
  imageRegistry: ""
  imagePullSecrets: []
  storageClass: ""

auth:
  rootPassword: "secret123"
  createDatabase: true
  database: "my_database"
  username: "admin"
  password: "secret123"
  replicationUser: replicator
  replicationPassword: ""
  existingSecret: ""
  usePasswordFiles: false
  customPasswordFiles: {}
  defaultAuthenticationPlugin: ""  

primary:
  service:    
    type: LoadBalancer
    annotations:
      service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
      service.beta.kubernetes.io/aws-load-balancer-type: external
      service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
      service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: instance   

serviceAccount:
  create: true
  name: "mysqlserviceaccount"
  annotations: 
    eks.amazonaws.com/role-arn: "arn:aws:iam::667294666490:role/auction-cluster-20241126163757775000000001"