global:  
  storageClass: "efs-sc"

# persistence:
#   enabled: true
#   storageClass: "efs-sc"

livenessProbe:
  enabled: true
  initialDelaySeconds: 60
  periodSeconds: 15
  timeoutSeconds: 10
  failureThreshold: 20
readinessProbe:
  enabled: true
  initialDelaySeconds: 60
  periodSeconds: 15
  timeoutSeconds: 10
  failureThreshold: 20
persistence:
  enabled: true
  storageClass: efs-sc
  accessModes:
    - ReadWriteOnce
  size: 100M  

backup:
  cronjob:
    storage:
      storageClass: "efs-sc"    

hidden:
  persistence:
    storageClass: "efs-sc"

auth:
  enabled: true  
  rootUser: root  
  rootPassword: "secret123"

serviceAccount:
  create: true  
  name: "mongodbservcieaccount"    
  annotations:
    eks.amazonaws.com/role-arn: "arn:aws:iam::667294666490:role/auction-cluster-20241126163757775000000001"  

service:  
  nameOverride: ""  
  type: LoadBalancer
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    service.beta.kubernetes.io/aws-load-balancer-type: external
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: instance  

podSecurityContext:
  enabled: true
  fsGroupChangePolicy: Always
  supplementalGroups: []
  fsGroup: 1000

containerSecurityContext:
  enabled: true
  seLinuxOptions: {}
  runAsUser: 1000
  runAsGroup: 1000


volumePermissions:
  enabled: true
