auth:
  enabled: true  
  rootUser: root  
  rootPassword: "secret123"

serviceAccount:  
  create: false

service:  
  type: NodePort

resources:
  requests:
    cpu: 1000m
    memory: 1G
  limits:
    cpu: 1000m
    memory: 1G  