image:
  registry: 172.16.16.2:30516
  repository: bitnamilegacy/mongodb
  tag: 8.0.3-debian-12-r0  

replicaCount: 1

metrics:  
  enabled: false  
  image:
    registry: 172.16.16.2:30516
    repository: bitnamilegacy/mongodb-exporter
    tag: 0.41.2-debian-12-r1    
    pullPolicy: IfNotPresent

auth:
  enabled: true  
  rootUser: root  
  rootPassword: "secret123"

serviceAccount:  
  create: false

service:  
  nameOverride: ""  
  type: NodePort

nodeSelector:
  node.name: node-1  

resources:
  requests:
    cpu: 1000m
    memory: 1G
  limits:
    cpu: 1000m
    memory: 1G  