controller:
  name: controller
  enableAnnotationValidations: false
  image:
    ## Keep false as default for now!
    chroot: false
    registry: 172.16.16.2:30516
    image: ingress-nginx/controller