image:
  registry: 172.16.16.2:30516
  repository: bitnami/rabbitmq
  tag: 3.12.12-debian-11-r0

auth:
  username: admin
  password: "admin"
  securePassword: true
  existingPasswordSecret: ""

serviceAccount:  
  create: false
  name: ""
  namespace: "default"
  awsRoleArn: ""
  owner: ""
  automountServiceAccountToken: true  
  annotations: {} 

service:  
  type: NodePort

nodeSelector:
  node.name: node-1

resources:
  requests:
    cpu: 1000m
    memory: 512Mi
  limits:
    cpu: 1000m
    memory: 512Mi