# Default values for authservice
replicaCount: 1

image:
  repository: 188.132.232.168:30836/authservice
  pullPolicy: IfNotPresent
  tag: "15"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 8083
  targetPort: 8083

ingress:
  enabled: true
  className: "cilium"
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    kubernetes.io/ingress.class: cilium
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: auth.bugx.ir
      paths:
        - path: /
          pathType: Prefix
  tls: 
   - secretName: authservice-tls
     hosts:
       - auth.bugx.ir

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi

autoscaling:
  enabled: false
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

# MongoDB configuration
mongodb:
  connectionString: "mongodb://root:jPRoAlzMyY@mongodb:27017/"
  database: "vcluster"
  collection: "users"

# JWT configuration
jwt:
  secret: "mysecret123"

# Application configuration
app:
  port: 8083

