{{- if and .Values.argocd .Values.argocd.token (not .Values.argocd.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "vclusterapi.fullname" . }}-argocd
  labels:
    {{- include "vclusterapi.labels" . | nindent 4 }}
type: Opaque
data:
  {{ .Values.argocd.secretKey }}: {{ .Values.argocd.token | b64enc | quote }}
{{- end }}

