apiVersion: v1
kind: Service
metadata:
  name: {{ include "vclusterapi.fullname" . }}
  labels:
    {{- include "vclusterapi.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http

    - name: delve
      port: 40000
      targetPort: delve
      protocol: TCP
      nodePort: 30040 

  selector:
    {{- include "vclusterapi.selectorLabels" . | nindent 4 }}

